language: java
dist: trusty
sudo: false
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
    - xmlstarlet
script:
- cp .travis.settings.xml $HOME/.m2/settings.xml
- ./fix_version.sh
- mvn package
- ./bundle_deb.sh
deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
cache:
  directories:
  - $HOME/.m2/