language: java
dist: trusty
sudo: false
jdk:
- openjdk8
addons:
  apt:
    packages:
    - openjfx
    - xmlstarlet
install: /bin/true
script:
- cp .travis.settings.xml $HOME/.m2/settings.xml
- ./fix_version.sh
- mvn package
- ./bundle_deb.sh
cache:
  directories:
  - $HOME/.m2
deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./deploy-unstable.sh
    skip_cleanup: true