language: java
dist: trusty
sudo: false
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
script:
- cp .travis.settings.xml $HOME/.m2/settings.xml
- mvn package
deploy:
  provider: script
  script: ./deploy_on_tag.sh
  skip_cleanup: true
  on:
    tags: true
