language: java
dist: trusty
sudo: false
jdk:
- openjdk8
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
script:
- mvn package
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -DskipTests
  skip_cleanup: true
  on:
    tags: true
