language: java
dist: trusty
sudo: false
jdk:
- openjdk8
before-install:
  - sudo apt-get install openjfx -y
script:
- mvn package
deploy:
  provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -DskipTests
  skip_cleanup: true
  on:
    tags: true
